/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assessments/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an exam attempt */
        post: operations["EspalierWeb.AttemptController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in to a demo account
         * @description Only with `AUTH_DEMO=true`; otherwise 404.
         */
        post: operations["EspalierWeb.Auth.DemoController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an invitation
         * @description Self-service invitation with `SIGNUP=invite` or `domain`; the answer is the same for every address. `SIGNUP=closed` and `LOCAL_ACCOUNTS=false` answer 404.
         */
        post: operations["EspalierWeb.Auth.InvitationController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation
         * @description Opens an enrollment session, which reaches only the enrollment routes.
         */
        post: operations["EspalierWeb.Auth.InvitationController.accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with a password
         * @description A correct password yields the pending second-factor state for five minutes and never a session. Known and unknown addresses receive the same answer.
         */
        post: operations["EspalierWeb.Auth.PasswordController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll in a program
         * @description Creates the enrollment (201). An existing enrollment answers 200 and takes the given path only while the learner has not chosen a path by hand.
         */
        post: operations["EspalierWeb.EnrollmentController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Choose the path
         * @description Sets the path and marks it as chosen by the learner.
         */
        patch: operations["EspalierWeb.EnrollmentController.update"];
        trace?: never;
    };
    "/api/items/{id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a practice item */
        post: operations["EspalierWeb.ItemResponseController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Request an e-mail change
         * @description Sends a confirmation link to the new address; the answer is the same for every address. Needs a second factor within the last 10 minutes.
         */
        put: operations["EspalierWeb.Me.EmailController.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an e-mail change */
        post: operations["EspalierWeb.Me.EmailController.confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change the password
         * @description Needs `current_password` and a second factor within the last 10 minutes; an enrollment or recovery session sets the password without them. Ends every other session and answers with a new session payload and CSRF token.
         */
        put: operations["EspalierWeb.Me.PasswordController.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the own progress in a program */
        get: operations["EspalierWeb.Me.ProgressController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the own sessions */
        get: operations["EspalierWeb.Me.SessionController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End one of the own sessions
         * @description Needs a second factor within the last 10 minutes.
         */
        delete: operations["EspalierWeb.Me.SessionController.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a module */
        get: operations["EspalierWeb.ModuleController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{id}/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a module */
        post: operations["EspalierWeb.ModuleCompletionController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the published programs */
        get: operations["EspalierWeb.ProgramController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a program */
        get: operations["EspalierWeb.ProgramController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{slug}/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the glossary of a program */
        get: operations["EspalierWeb.ProgramController.glossary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{slug}/handbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the handbook of a program
         * @description Every rule with its statement and action grouped by module, plus the keys of the program's placeholder blocks (README section 7, domain rule 10).
         */
        get: operations["EspalierWeb.ProgramController.handbook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the session payload
         * @description The user, roles, session strength, CSRF token, providers and flags; `user`, `session` and `pending` are `null` when absent.
         */
        get: operations["EspalierWeb.SessionController.show"];
        put?: never;
        post?: never;
        /** Sign out */
        delete: operations["EspalierWeb.SessionController.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the external identity providers
         * @description The public entries of the configured providers in configured order.
         */
        get: operations["EspalierWeb.ProviderController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Accepted
         * @description The request was accepted.
         */
        Accepted: {
            /** @enum {string} */
            status: "accepted";
        };
        /**
         * ProgramView
         * @description A published program.
         */
        ProgramView: {
            companion_formats: components["schemas"]["CompanionFormatView"][];
            /** Format: uuid */
            id: string;
            locale: string;
            /** @description The modules in number order. */
            modules: {
                /** Format: uuid */
                id: string;
                number: number;
                phases: ("orient" | "understand" | "apply" | "anchor" | "update")[];
                /** @description True when the module ignores the path. */
                single_path: boolean;
                summary: string;
                title: string;
            }[];
            pack_version: string;
            /** @description The segments of the self-assessment station. */
            segments: {
                /** @enum {string} */
                default_path: "short" | "full";
                description: string;
                key: string;
                label: string;
            }[];
            slug: string;
            /** @description The stations of the learner journey in order. */
            stations: {
                /** @description The introduction of the station. */
                intro: string | null;
                /** @enum {string} */
                kind: "self_assessment" | "overview" | "module" | "credential" | "companion_formats" | "feedback";
                /**
                 * Format: uuid
                 * @description The module of a module station.
                 */
                module_id: string | null;
                position: number;
                /** @description The question of the self-assessment station. */
                question: string | null;
                /** @description The questions of the feedback station. */
                questions: {
                    key: string;
                    /** @enum {string} */
                    kind: "single_choice" | "scale" | "free_text";
                    label: string;
                    /** @description The options of a `single_choice` question. */
                    options: {
                        key: string;
                        label: string;
                    }[];
                }[];
                title: string;
            }[];
            title: string;
        };
        /**
         * Handbook
         * @description Every rule with its statement and action.
         */
        Handbook: {
            /** @description The modules in number order with their rules. */
            modules: {
                /** Format: uuid */
                id: string;
                number: number;
                rules: {
                    action: string;
                    number: number;
                    statement: string;
                }[];
                title: string;
            }[];
            /** @description The keys of the policies that placeholder blocks name. */
            placeholders: string[];
        };
        /**
         * NextStep
         * @description The sign-in continues with a second factor.
         */
        NextStep: {
            /** @enum {string} */
            next: "second_factor";
        };
        /**
         * EmailChangeRequest
         * @description Requests an e-mail change; the link goes to the new address.
         */
        EmailChangeRequest: {
            /** @description The new e-mail address. */
            email: string;
        };
        /**
         * ObjectiveEvidence
         * @description An item or a format that shows the objective.
         */
        ObjectiveEvidence: {
            /**
             * Format: uuid
             * @description The id of the item or of the companion format.
             */
            id: string;
            /** @enum {string} */
            kind: "item" | "format";
        };
        /**
         * EmailConfirmRequest
         * @description Confirms an e-mail change.
         */
        EmailConfirmRequest: {
            /** @description The token of the confirmation link. */
            token: string;
        };
        /**
         * InvitationAcceptRequest
         * @description Accepts an invitation and opens an enrollment session.
         */
        InvitationAcceptRequest: {
            /** @description The token of the invitation link. */
            token: string;
        };
        /**
         * AttemptRequest
         * @description The answers of an exam attempt.
         */
        AttemptRequest: {
            /** @description Every item id of the exam mapped to its answer. A missing or unknown item id answers 422 with `fields.answers` `incomplete`. */
            answers: {
                [key: string]: components["schemas"]["Answer"];
            };
        };
        /**
         * EmptyRequest
         * @description No members.
         */
        EmptyRequest: Record<string, never>;
        /**
         * Answer
         * @description An answer to an item, with the members of the item's kind.
         */
        Answer: {
            /** @description Case key to the chosen category key. */
            cases?: {
                [key: string]: string;
            };
            /** @description The keys of the checks that are set. */
            checks?: string[];
            /** @description The initials that confirm a checklist drill; 2 to 5 characters count. */
            initials?: string;
            /** @description The chosen option keys. */
            options?: string[];
            /** @description Slot key to the chosen option key. */
            slots?: {
                [key: string]: string;
            };
        };
        /**
         * PasswordChangeRequest
         * @description Changes the password.
         */
        PasswordChangeRequest: {
            /** @description The current password. */
            current_password?: string;
            /** @description The new password, 15 to 128 code points after NFC. */
            password: string;
        };
        /**
         * Error
         * @description An error code without internals.
         */
        Error: {
            /** @description The error code. */
            error: string;
            /** @description For `validation_failed`: the error codes per member. */
            fields?: {
                [key: string]: string[];
            };
        };
        /**
         * ItemView
         * @description A practice or exam item without its answer key.
         */
        ItemView: {
            /** @description The cases of a classification. */
            cases: {
                key: string;
                text: string;
            }[];
            /** @description The categories of a classification. */
            categories: {
                key: string;
                label: string;
            }[];
            /** @description The checks of a checklist drill. */
            checks: {
                key: string;
                label: string;
                required: boolean;
            }[];
            /** Format: uuid */
            id: string;
            key: string;
            /** @enum {string} */
            kind: "single_choice" | "multiple_choice" | "slot_builder" | "classification" | "checklist_drill" | "poll";
            /**
             * Format: uuid
             * @description The lesson of a practice item.
             */
            lesson_id: string | null;
            /** @description The sorted keys of the objectives the item serves. */
            objective_keys: string[];
            /** @description The options of a choice item or a poll. */
            options: {
                key: string;
                label: string;
            }[];
            /** @enum {string} */
            provenance: "invented" | "sourced" | "vendor_statement" | "assumption" | "placeholder";
            /** @description The slots of a slot builder with their options. */
            slots: {
                key: string;
                label: string;
                options: {
                    key: string;
                    label: string;
                }[];
            }[];
            stem: string;
        };
        /**
         * ModuleView
         * @description The content of a module without answer keys.
         */
        ModuleView: {
            exams: {
                counts_for_credential: boolean;
                /** Format: uuid */
                id: string;
                /** @description The exam items in order. */
                items: components["schemas"]["ItemView"][];
                key: string;
                max_wrong: number;
                title: string;
            }[];
            /** Format: uuid */
            id: string;
            /** @description The lessons in position order. */
            lessons: {
                blocks: {
                    /** @description Markdown. */
                    body: string;
                    citations: {
                        locator: string | null;
                        source: {
                            /** Format: date */
                            edition_date: string;
                            key: string;
                            /** @enum {string} */
                            kind: "law" | "guidance" | "vendor" | "study" | "press" | "other";
                            publisher: string;
                            /** Format: date */
                            retrieved_on: string;
                            title: string;
                            url: string | null;
                        };
                    }[];
                    /** @description The paths on which the block starts collapsed. */
                    collapsed_on: ("short" | "full")[];
                    /** @enum {string} */
                    kind: "text" | "explanation" | "example" | "case_comparison" | "quote" | "callout" | "placeholder";
                    /** @description The policy that a placeholder block renders. */
                    placeholder_key: string | null;
                    /** @enum {string} */
                    provenance: "invented" | "sourced" | "vendor_statement" | "assumption" | "placeholder";
                }[];
                /** Format: uuid */
                id: string;
                key: string;
                position: number;
                title: string;
            }[];
            number: number;
            /** @description The objectives of the topic in position order. */
            objectives: components["schemas"]["ObjectiveView"][];
            phases: ("orient" | "understand" | "apply" | "anchor" | "update")[];
            /** @description The items that no exam lists. */
            practice_items: components["schemas"]["ItemView"][];
            program_slug: string;
            /** @description The rules in number order. */
            rules: {
                action: string;
                citations: {
                    locator: string | null;
                    source: {
                        /** Format: date */
                        edition_date: string;
                        key: string;
                        /** @enum {string} */
                        kind: "law" | "guidance" | "vendor" | "study" | "press" | "other";
                        publisher: string;
                        /** Format: date */
                        retrieved_on: string;
                        title: string;
                        url: string | null;
                    };
                }[];
                /** Format: uuid */
                id: string;
                number: number;
                statement: string;
            }[];
            /** @description True when the module ignores the path. */
            single_path: boolean;
            summary: string;
            title: string;
        };
        /**
         * SessionPayload
         * @description The session of the browser.
         */
        SessionPayload: {
            /** @description The token for the `x-csrf-token` header. */
            csrf_token: string;
            flags: {
                admin_passkey_required: boolean;
                /** @description Mirrors `AUTH_DEMO`. */
                demo: boolean;
                local_accounts: boolean;
                /** @enum {string} */
                signup: "closed" | "invite" | "domain";
            };
            /** @description The pending second-factor state after a first factor. */
            pending: {
                /** Format: date-time */
                expires_at: string;
                /** @enum {string} */
                next: "second_factor";
            } | null;
            providers: {
                /** @description The provider key of the configuration. */
                key: string;
                /**
                 * @description A redirect to the provider or a credentials form.
                 * @enum {string}
                 */
                kind: "redirect" | "credentials";
                label: string;
                /** @description The path where the sign-in starts. */
                start_url: string;
                /** @enum {string} */
                type: "entra" | "google" | "oidc" | "ldap";
            }[];
            roles: ("learner" | "facilitator" | "author" | "registrar" | "analyst" | "admin")[];
            session: {
                auth_methods: ("passkey" | "password" | "totp" | "recovery_code" | "email_code" | "oidc" | "ldap" | "idp_mfa" | "demo")[];
                /** Format: date-time */
                expires_at: string;
                idle_timeout_minutes: number;
                /** @description The provider of the session row; `null` for local and demo. */
                provider_key: string | null;
                /**
                 * Format: date-time
                 * @description The end of the 10-minute window of a recent second factor.
                 */
                recent_auth_until: string | null;
                /** @enum {string} */
                strength: "mfa" | "recovery" | "enrollment" | "demo";
            } | null;
            user: {
                display_name: string | null;
                /** @description `null` for demo accounts and accounts without an address. */
                email: string | null;
                /** Format: uuid */
                id: string;
                locale: string;
            } | null;
        };
        /**
         * EnrollmentRequest
         * @description Enrolls the signed-in user in a program.
         */
        EnrollmentRequest: {
            /**
             * @description The path preselected from the segment default.
             * @enum {string}
             */
            path: "short" | "full";
            /** @description The slug of a published program. */
            program_slug: string;
        };
        /**
         * ModuleCompletionView
         * @description The completion of a module.
         */
        ModuleCompletionView: {
            /** Format: date-time */
            completed_at: string;
            /** Format: uuid */
            module_id: string;
        };
        /**
         * ItemResponseRequest
         * @description A practice answer. The answer is evaluated and stored nowhere.
         */
        ItemResponseRequest: {
            answer: components["schemas"]["Answer"];
        };
        /**
         * ItemResult
         * @description The evaluation of an answer.
         */
        ItemResult: {
            /** @description `null` for a poll. */
            correct: boolean | null;
            /** Format: uuid */
            item_id: string;
            option_feedback: {
                choice?: string | null;
                correct: boolean;
                expected?: string | null;
                feedback?: string | null;
                /** @description The key of the option, slot, case or check. */
                key: string;
                required?: boolean;
                selected?: boolean;
            }[];
            /** @description Lessons whose explanations expand after a wrong answer on the short path; empty unless the answer is wrong. */
            reveals: string[];
            /** @description The rules that the item refers to. */
            rules: {
                action: string;
                /** Format: uuid */
                id: string;
                number: number;
                statement: string;
            }[];
        };
        /**
         * InvitationRequest
         * @description A self-service invitation request.
         */
        InvitationRequest: {
            /** @description The e-mail address to invite. */
            email: string;
        };
        /**
         * ObjectiveView
         * @description A learning objective of the topic.
         */
        ObjectiveView: {
            /**
             * @description The CORE competence area.
             * @enum {string}
             */
            area: "subject" | "method" | "self" | "social";
            /** @enum {string} */
            depth: "know" | "apply" | "judge";
            /** @description One of the module's content domains. */
            domain: string | null;
            /** @description The evidence items ordered by key, followed by the evidence formats ordered by key. */
            evidence: components["schemas"]["ObjectiveEvidence"][];
            key: string;
            /** @description The teaching lessons, in lesson position order. */
            lesson_ids: string[];
            /** @enum {string} */
            phase: "orient" | "understand" | "apply" | "anchor" | "update";
            statement: string;
        };
        /**
         * Progress
         * @description The progress of the signed-in user in a program.
         */
        Progress: {
            /** @description The answered items; present only with `TRACKING_DETAIL=standard`. */
            answered_item_ids?: string[];
            completed_module_ids: string[];
            /** @description The enrollment, or `null` without one. */
            enrollment: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                path: "short" | "full";
                path_chosen_manually: boolean;
            } | null;
            /** @description Per exam with an attempt: `passed` when any attempt passed, otherwise the outcome of the latest attempt. */
            exams: {
                /** Format: uuid */
                assessment_id: string;
                /** @enum {string} */
                outcome: "passed" | "failed_core" | "failed_errors";
            }[];
            /** @description Every objective of the program, ordered by module number and position. */
            objectives: components["schemas"]["ObjectiveProgress"][];
        };
        /**
         * EnrollmentView
         * @description The enrollment of the signed-in user.
         */
        EnrollmentView: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            path: "short" | "full";
            /** @description True after the learner chose the path by hand. */
            path_chosen_manually: boolean;
            /** Format: uuid */
            program_id: string;
            /** Format: date-time */
            started_at: string;
        };
        /**
         * EnrollmentPathRequest
         * @description Sets the path by the learner's choice.
         */
        EnrollmentPathRequest: {
            /**
             * @description The path the learner chose.
             * @enum {string}
             */
            path: "short" | "full";
        };
        /**
         * ObjectiveProgress
         * @description Whether the learner's records show evidence.
         */
        ObjectiveProgress: {
            key: string;
            /** @enum {string} */
            status: "evidenced" | "open";
        };
        /**
         * ProviderList
         * @description The external identity providers.
         */
        ProviderList: {
            /** @description In configured order. */
            providers: {
                /** @description The provider key of the configuration. */
                key: string;
                /**
                 * @description A redirect to the provider or a credentials form.
                 * @enum {string}
                 */
                kind: "redirect" | "credentials";
                label: string;
                /** @description The path where the sign-in starts. */
                start_url: string;
                /** @enum {string} */
                type: "entra" | "google" | "oidc" | "ldap";
            }[];
        };
        /**
         * Glossary
         * @description The glossary of a program.
         */
        Glossary: {
            /** @description The terms ordered by slug. */
            terms: {
                label: string;
                short_text: string;
                slug: string;
            }[];
        };
        /**
         * ProgramList
         * @description The published programs, ordered by slug.
         */
        ProgramList: {
            programs: {
                /** @description The language tag of the content. */
                locale: string;
                /** @description The key of the content pack. */
                slug: string;
                title: string;
            }[];
        };
        /**
         * CompanionFormatView
         * @description A format held outside the platform.
         */
        CompanionFormatView: {
            /** @description True when an attendance certificate provides evidence. */
            attendance_counts: boolean;
            description: string;
            /** Format: uuid */
            id: string;
            key: string;
            phases: ("orient" | "understand" | "apply" | "anchor" | "update")[];
            title: string;
        };
        /**
         * PasswordSignInRequest
         * @description A password sign-in; it yields the pending second-factor state.
         */
        PasswordSignInRequest: {
            /** @description The e-mail address. */
            email: string;
            /** @description The password. */
            password: string;
        };
        /**
         * DemoSignInRequest
         * @description A demo sign-in with `AUTH_DEMO=true`.
         */
        DemoSignInRequest: {
            slot: number;
        };
        /**
         * AssessmentsOpenError
         * @description The open exams of the module.
         */
        AssessmentsOpenError: {
            /** @description The exams without a passed attempt. */
            assessments: {
                /** Format: uuid */
                id: string;
                key: string;
                title: string;
            }[];
            /** @enum {string} */
            error: "assessments_open";
        };
        /**
         * AttemptResult
         * @description An exam attempt under the pass rule.
         */
        AttemptResult: {
            /** Format: uuid */
            assessment_id: string;
            core_failed: boolean;
            /** Format: uuid */
            id: string;
            /** @description The number of the attempt, from 1. */
            number: number;
            /** @enum {string} */
            outcome: "passed" | "failed_core" | "failed_errors";
            /** @description The evaluation per item in exam order. */
            results: components["schemas"]["ItemResult"][];
            /** Format: date-time */
            submitted_at: string;
            wrong_count: number;
        };
        /**
         * SessionList
         * @description The sessions of the signed-in user.
         */
        SessionList: {
            sessions: {
                auth_methods: ("passkey" | "password" | "totp" | "recovery_code" | "email_code" | "oidc" | "ldap" | "idp_mfa" | "demo")[];
                /** Format: date-time */
                authenticated_at: string;
                /** @description True on the calling session. */
                current: boolean;
                /** @description The device summary of the user agent. */
                device: string | null;
                /** Format: date-time */
                expires_at: string;
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                last_seen_at: string;
                /** @enum {string} */
                strength: "mfa" | "recovery" | "enrollment" | "demo";
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "EspalierWeb.AttemptController.create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The exam id. */
                id: string;
            };
            cookie?: never;
        };
        /** @description The answers */
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptRequest"];
            };
        };
        responses: {
            /** @description The attempt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_enrolled` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Auth.DemoController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The demo slot */
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoSignInRequest"];
            };
        };
        responses: {
            /** @description The session payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPayload"];
                };
            };
            /** @description Error codes: `bad_request` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Auth.InvitationController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The address */
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Error codes: `bad_request` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Auth.InvitationController.accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The invitation token */
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            /** @description The session payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPayload"];
                };
            };
            /** @description Error codes: `invalid_token` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Auth.PasswordController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The address and the password */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordSignInRequest"];
            };
        };
        responses: {
            /** @description The next step */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextStep"];
                };
            };
            /** @description Error codes: `bad_request` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `invalid_credentials` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.EnrollmentController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The program and the path */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description The existing enrollment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentView"];
                };
            };
            /** @description The new enrollment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentView"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.EnrollmentController.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The enrollment id. */
                id: string;
            };
            cookie?: never;
        };
        /** @description The path */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentPathRequest"];
            };
        };
        responses: {
            /** @description The enrollment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentView"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ItemResponseController.create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The item id. */
                id: string;
            };
            cookie?: never;
        };
        /** @description The answer */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemResponseRequest"];
            };
        };
        responses: {
            /** @description The evaluation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResult"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_enrolled` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Me.EmailController.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new address */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChangeRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Error codes: `bad_request` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `reauth_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Me.EmailController.confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The confirmation token */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailConfirmRequest"];
            };
        };
        responses: {
            /** @description The session payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPayload"];
                };
            };
            /** @description Error codes: `invalid_token` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `reauth_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Me.PasswordController.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The current and the new password */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description The session payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPayload"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `forbidden`, `reauth_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Me.ProgressController.show": {
        parameters: {
            query: {
                /** @description The slug of a published program. */
                program: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Me.SessionController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.Me.SessionController.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `reauth_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ModuleController.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The module id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The module */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleView"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ModuleCompletionController.create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The module id. */
                id: string;
            };
            cookie?: never;
        };
        /** @description No members */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description The completion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleCompletionView"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `assessments_open` with the open exams, or `not_enrolled` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentsOpenError"] | components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `rate_limited` */
            429: {
                headers: {
                    /** @description Seconds until the bucket admits the next request. */
                    "retry-after"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ProgramController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published programs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramList"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ProgramController.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The slug of a published program. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The program */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramView"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ProgramController.glossary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The slug of a published program. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The glossary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Glossary"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ProgramController.handbook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The slug of a published program. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The handbook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Handbook"];
                };
            };
            /** @description Error codes: `unauthenticated` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `enrollment_required`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error codes: `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.SessionController.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPayload"];
                };
            };
            /** @description Error codes: `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.SessionController.delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error codes: `csrf`, `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "EspalierWeb.ProviderController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
            /** @description Error codes: `cross_site_request` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
