import Config

# Host port of the database from compose.dev.yaml (DATABASE_PORT in .env).
# An empty value counts as unset.
database_port =
  case String.trim(System.get_env("DATABASE_PORT", "")) do
    "" -> 5432
    port -> String.to_integer(port)
  end

# Configure your database
config :espalier, Espalier.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: database_port,
  database: "espalier_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :espalier, EspalierWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: String.duplicate("d", 64),
  watchers: [npm: ["run", "dev", cd: Path.expand("../frontend", __DIR__)]]

# GET /api/openapi builds the document on every request, so that a reloaded
# controller shows its new operation (task 0009). Other environments keep the
# default cache in :persistent_term.
config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable development-only routes. The mailbox preview is gone (Mailpit
# replaces it); task 0011 mounts its development routes behind this flag.
config :espalier, dev_routes: true

# Development mail goes to Mailpit from compose.dev.yaml (UI at
# http://localhost:8025).
config :espalier, Espalier.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "localhost",
  port: 1025,
  ssl: false,
  tls: :never,
  auth: :never,
  no_mx_lookups: true,
  retries: 1

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Passkeys: the browser opens the SPA on the Vite port (task 0005).
config :espalier, :webauthn, rp_id: "localhost", origins: ["http://localhost:5173"]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Invented keys for local data only. Production keys come from CLOAK_KEY_V<n>
# and CLOAK_HMAC_SECRET (config/runtime.exs).
config :espalier, Espalier.Vault, keys: [{1, Base.encode64(String.duplicate("d", 32))}]
config :espalier, Espalier.Hashed.HMAC, secret: Base.encode64(String.duplicate("h", 32))

# Mock OIDC provider of test/support/dev_oidc/ (task 0006, `make dev-oidc`).
# The fixture secret works only against the mock, and the tenant id is
# invented. allow_unsafe_http admits the http:// end-session endpoint of the
# mock on localhost; no other configuration sets it.
oidc_public_url =
  case String.trim(System.get_env("PUBLIC_URL", "")) do
    "" -> "http://localhost:5173"
    url -> url |> String.trim("\"") |> String.trim_trailing("/")
  end

config :espalier, :dev_children, [{Espalier.DevOidc, port: 4010}]

config :espalier, Espalier.DevOidc,
  client_id: "espalier-dev",
  client_secret: "dev-oidc-fixture-secret",
  tenant_id: "3f0c2a9e-7b1d-4e5a-8c6f-2d9b0e4a1c7d",
  redirect_uris:
    for(key <- ["entra", "google", "oidc"], do: "#{oidc_public_url}/auth/oidc/#{key}/callback"),
  post_logout_redirect_uris: ["#{oidc_public_url}/signed-out"]

config :espalier, Espalier.Identity.Oidc, allow_unsafe_http: true
