defmodule EspalierWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :espalier

  # The endpoint has no session. The session cookies are configured in the
  # router pipelines with the options of EspalierWeb.TransactionCookie.

  # The client address and the security headers apply to every response,
  # the SPA, the static assets, /health and the API included.
  plug EspalierWeb.Plugs.TrustedProxy
  plug EspalierWeb.Plugs.SecurityHeaders

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :espalier,
    gzip: not code_reloading?,
    only: EspalierWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :espalier
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.Head
  plug EspalierWeb.Router
end
